# fly.toml app configuration file generated for travel-planner-api-weathered-tree-9345 on 2026-02-10T21:07:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'travel-planner-api-weathered-tree-9345'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[env]
  app = "travel-planner"
  ENVIRONMENT = 'production'
  PORT = '8000'
  WORKERS = '1'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[checks]
  [checks.health]
    port = 8000
    type = 'http'
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    path = '/health'

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
